name: Build

on: 
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [20.x]
	
    steps:
    - uses: actions/checkout@v2
    - name: Use node.js ${matrix.node-version}}
      uses: action/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}	
    - run: npm install
    - run: npm test
